---
- name: packages
  apt:
    name: sanoid
    force_apt_get: yes
    update_cache: yes
    state: present

- name: config directory
  file:
    path: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: config file
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: "0644"

- name: cron
  cron:
    user: root
    state: present
    name: sanoid
    job: TZ=UTC sanoid --cron
    special_time: "{{ cron_interval | default('hourly') }}"
